version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.62
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.11
    - 1.17.12
    - 1.17.13
    - 1.17.14
    - 1.17.15
    - 1.17.16
    - 1.17.17
    - 1.17.18
    - 1.17.19
    - 1.17.2
    - 1.17.20
    - 1.17.21
    - 1.17.22
    - 1.17.23
    - 1.17.24
    - 1.17.25
    - 1.17.26
    - 1.17.27
    - 1.17.28
    - 1.17.29
    - 1.17.3
    - 1.17.30
    - 1.17.32
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.43
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.58
    - 1.17.59
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
    - 2.8.1
  - dependency-name: certbot
    versions:
    - 1.11.0
    - 1.12.0
    - 1.13.0
  - dependency-name: acme
    versions:
    - 1.11.0
    - 1.12.0
    - 1.13.0
  - dependency-name: tox
    versions:
    - 3.21.3
    - 3.21.4
    - 3.22.0
    - 3.23.0
  - dependency-name: cryptography
    versions:
    - 3.3.2
  - dependency-name: bleach
    versions:
    - 3.3.0
  - dependency-name: pyyaml
    versions:
    - 5.4.1
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: localzone
    versions:
    - 0.9.8
  - dependency-name: dnspython
    versions:
    - 2.1.0
